In [1]:
# Todo: Make stratified train test split (both train and test must have the same amount of target classes in them) of features x and y
# stratiefied means that the ratio of 0 & 1 in the target y is the same in both splits.
# hint: look at sklearn documentation, you are of course encouraged to use sklearn functions.
# expected output is a list with 4 items (x_train, x_test, y_train, y_test)
# e.g. for the provided test input, the expected outcome is something like this:
# [array([12,  7,  2,  5,  9, 10, 14]), array([ 6, 11,  8,  1, 15, 13,  3,  4]), array([1, 0, 0, 0, 0, 1, 1]), array([0, 1, 0, 0, 1, 1, 0, 0])]
# so that x_train, x_test, y_train, y_test = split_50_50(x, y) then contains the correct splits

import numpy as np

def split_50_50(x, y):
    return None, None, None, None


x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  1,  1,  1])
x_train, x_test, y_train, y_test = split_50_50(x, y)
print(split_50_50(x, y))

(None, None, None, None)


In [ ]:
# Todo: scale the given vector with a min/max scaler
# * find the corresponding function in skelarn
# *** (optional) implement it yourself and compare your results with the sklearn function
# *** (optional) add other scalers aswell

import numpy as np

def scale_this(x):
    pass

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]).reshape(-1, 1)
print(scale_this(x))


In [ ]:
from matplotlib import pyplot as plt
import numpy as np


# Todo: Scoring - calculate mean square error, mean absolute error, mean absolute percentage error, and r2 of the following prediction from a regression problem
# * Calculate the scores, check out sklearn documentation
# * Explain why mape showing such high values?

def do_scoring(y_true, y_pred):
    print(f'mse: ?')
    print(f'mae: ?')
    print(f'mape: ?')
    print(f'r2: ?')


x = np.arange(0, np.pi*2, 0.1)
y_true = np.sin(x)
y_pred_1 = y_true + 0.05
y_pred_2 = np.roll(y_true, shift=1)
y_pred_3 = y_true + np.random.random(len(y_true))*0.1
y_pred_4 = np.zeros(len(y_true))
y_pred_5 = y_true

plt.plot(x, y_true)
plt.plot(x, y_pred_1)
plt.plot(x, y_pred_2)
plt.plot(x, y_pred_3)
plt.plot(x, y_pred_4)
plt.legend(['y_true', 'y_pred_1', 'y_pred_2', 'y_pred_3', 'y_pred_4'])
plt.show()

do_scoring(y_true, y_pred_1)
do_scoring(y_true, y_pred_2)
do_scoring(y_true, y_pred_3)
do_scoring(y_true, y_pred_4)
do_scoring(y_true, y_pred_5)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

# Todo: Generate polynomial features
# * create polynomial features of degree 2 for the given data z
# output should look something like this:
# [[    1.    11.     1.    11.   121.]
#  [    2.    21.     4.    42.   441.]
#  [    3.    31.     9.    93.   961.]
#  [    4.    41.    16.   164.  1681.]
#  [    5.    51.    25.   255.  2601.]
#  [    6.    61.    36.   366.  3721.]
#  [    7.    71.    49.   497.  5041.]
#  [    8.    81.    64.   648.  6561.]
#  [    9.    91.    81.   819.  8281.]
#  [   10.   101.   100.  1010. 10201.]
#  [   11.   111.   121.  1221. 12321.]
#  [   12.   121.   144.  1452. 14641.]
#  [   13.   131.   169.  1703. 17161.]
#  [   14.   141.   196.  1974. 19881.]
#  [   15.   151.   225.  2265. 22801.]]

def make_polynomial_features(x, degree):
    pass

z = np.array([[  1,  11],
               [  2,  21],
               [  3,  31],
               [  4,  41],
               [  5,  51],
               [  6,  61],
               [  7,  71],
               [  8,  81],
               [  9,  91],
               [ 10, 101],
               [ 11, 111],
               [ 12, 121],
               [ 13, 131],
               [ 14, 141],
               [ 15, 151]])
print(str(make_polynomial_features(z, 2)))